### ISSUE TITLE
Retrieving Actions

### ISSUE THREAD

**Issue by genalipsis** [kontaktio/SDK-iOS#10]
KONTAKT_SDK_VERSION @"5.4"

Beacon objects do not have Actions even though actions have been assigned in the Admin Panel.

     self.client = [KTKClient new];
      [_client setApiKey:MyKey];
      KTKAction *action = [_client actionByUUID:aUUID withError:&error];

action is always null 

       NSArray *beacons = [_client beaconsWithError:&error];
      //I do get an array of beacon objects

        for (KTKBeacon *aBeacon in beacons) {

                  KTKAction *action = [_client actionByUUID:aBeacon.managerUUID withError:&error];
        
                 NSArray *actions = [aBeacon.actions allObjects];
                NSLog(@"%@\t%@\t%@\t%@\t%@\t%@", aBeacon.managerUUID, [aBeacon.major stringValue], [aBeacon.minor stringValue], aBeacon.uniqueID, aBeacon.alias, aBeacon.name);
        
                 for (KTKAction *anAction in actions) {
                 //actions are always null as well
                 NSLog(@"url: %@\tproximity:%@", anAction.url, anAction.proximity);
            
                 }
          }

![panel___kontakt](https://cloud.githubusercontent.com/assets/2452564/7860694/4acd5ce0-0519-11e5-9b9e-5174a198dc47.jpg)

![jmbeaconmanager_m_jpg](https://cloud.githubusercontent.com/assets/2452564/7954442/e7a4b878-09cf-11e5-9304-5f55478cd63e.jpg)

**Comment by hlebowicz-kontakt** [comment]
Hi @genalipsis,

To get actions assigned to beacon you have to ask for this specific one by one of methods:
   
    - (KTKBeacon *)beaconByUniqueID:(NSString *)uniqueID withError:(NSError **)error;
or 

    - (KTKBeacon *)beaconByUUID:(NSString *)UUID major:(NSNumber *)major minor:(NSNumber *)minor withError:(NSError **)error;
Then you will get KTKBeacon objects with actions.

Additionally if you want to get action using:

    - (KTKAction *)actionByUUID:(NSString *)UUID withError:(NSError **)error;
Then you should provide action's UUID not manager's one.

*Today we released version 5.5 with some updates, enjoy.*

Lukasz

**Comment by genalipsis** [comment]
Thanks @hlebowicz-kontakt , I can get actions using one of the two methods your suggested. 

FYI: For getting actions

Works
    - (KTKBeacon *)beaconByUUID:(NSString *)UUID major:(NSNumber *)major minor:(NSNumber *)minor withError:(NSError **)error;


Does not work
   - (KTKBeacon *)beaconByUniqueID:(NSString *)uniqueID withError:(NSError **)error;


![jmbeaconmanager_m](https://cloud.githubusercontent.com/assets/2452564/8042562/5cabf114-0e20-11e5-9a38-eb6a8fd5e9c1.jpg)

**Comment by hlebowicz-kontakt** [comment]
Second method works but there was a bug in version 5.4 that's why I advised you to update to 5.5 ;)
