### ISSUE TITLE
Help with characteristic descriptors

### ISSUE THREAD

**Issue by vple** [kontaktio/SDK-iOS#11]
Hi,

I was having a problem reading characteristic descriptor values and the Kontakt support team suggested that I make an issue here.

I think that I am either connecting to the beacon incorrectly or that I am incorrectly calling the methods to get the descriptor values. This isn't verbatim, but my code looks roughly like this:

```
if let beacon = device as? KTKBeaconDevice {
    if (beacon.uniqueID == master.beacon?.providerId) {
        var error : NSError? = nil
        var success = beacon.connectWithPassword(master.password.text, andError: &error)
        if (success) {
            var descriptor : KTKCharacteristicDescriptor
            var error : NSError?

            descriptor = beacon.characteristicDescriptorWithType(kKTKCharacteristicDescriptorTypeMinor)
            error? = beacon.readValueForCharacteristicWithDescriptor(descriptor)
            if let e = error {
                // do something
            } else {
                var data = beacon.dataForCharacteristicWithDescriptor(descriptor)
                var s = beacon.stringForCharacteristicWithDescriptor(descriptor)
                println(data)
                println(s)
            }
            master.ktkBeaconManager.stopFindingDevices()
        }
    }
 }
```

I didn't see any errors when running my code. The console prints out:
```
nil
0
```

I'm not sure which version of the SDK I'm using, but I downloaded it from here:
https://github.com/kontaktio/SDK-iOS/archive/master.zip
a few days ago.

I've been working off of the instructions from here:
http://docs.kontakt.io/ios-sdk/quickstart/#beacon-configuration
These docs mention using KTKBeaconDevice's setPassword, connect, discover, and authorize methods, although xcode provides me with an error that I should use connectWithPassword instead.

Could you explain what I'm doing incorrectly and/or provide a code example for me to work off of?

**Comment by hlebowicz-kontakt** [comment]
Honestly, your code is looking ok. 
I am not sure why you are not getting values...
Try to call:

    - (BOOL)isCharacteristicWithDescriptorReadable:(KTKCharacteristicDescriptor *)descriptor;

before reading value.
If you downloaded it from master than you should have the newest one.

Additionally check if you have proper characteristic's descriptor returned.

**Comment by vple** [comment]
We resolved the issue. Apparently the code above didn't work with swift, but when we changed it to objective-c it worked fine.
