### ISSUE TITLE
Undefined symbols for architecture i386:

### ISSUE THREAD

**Issue by haoroadhouse** [kontaktio/SDK-iOS#12]
It seems the SDK is missing the architecture for i386.

This can be reproduced by install from cocoapod by using

pod 'KontaktSDK', '~>5.5’

And then select either iPhone 4s or iPhone 5 simulator and select build.

**Comment by hlebowicz-kontakt** [comment]
Hi,

It's not a bug - we don't support old 32-bit architecture.
You should remove it from your project settings and replace with **x86_64**.
