### ISSUE TITLE
CocoaPods Installation Issue

### ISSUE THREAD

**Issue by doguhanokumus** [kontaktio/SDK-iOS#13]
I'm having trouble with trying to integrate KontaktSDK into my project using CocoaPods (ios 8.3). my app is targeting ios 8+, and is written in Swift, thus the podfile looks like this:

    platform :ios, '8.0'
    use_frameworks!

    target 'XxX' do
 
    pod 'KontaktSDK'
    ....and so on

And in my project I try to import the SDK

    import KontaktSDK

but it gives me "No such module 'KontaktSDK' error. 

Am I missing something here? If not, your SDK might not be compatible with "use_frameworks!" flag, which is basically mandatory for projects using pods written in swift (I do have quite a few of those)

**Comment by hlebowicz-kontakt** [comment]
Hey,

It looks like there is something wrong with your Podfile.
Try **pod install** and let me know what was the result.

Also please check in your pod project's targets if library is attached.

**Comment by doguhanokumus** [comment]
Hey,

I removed the KontaktSDK and ran *pod install* once again, it installed without any problems but nothing changed. 

Then I started a clean project, ran *pod init* and installed KontaktSDK, this time without using the "use_frameworks!" flag. It compiled perfectly. Changing the podfile back to "use_frameworks!", I started getting the same error. So, it is def. related to that flag. the cocoapods version is: 0.37.2

**Comment by doguhanokumus** [comment]
btw, I managed to install your sdk manually without any problems. But, we are already using pods so it would be easier for us to use pods over manual installation in future releases

**Comment by hlebowicz-kontakt** [comment]
Hi,

The problem is that our library is a static lib not a framework.
That's why you won't see it in **targets** section.

You just need to **import Pods** and you will get access to our classes etc.

Next release of our library will be a framework not a static lib - stay tuned ;)
