### ISSUE TITLE
Delegate Methods are not called always

### ISSUE THREAD

**Issue by amjad36** [kontaktio/SDK-iOS#15]
Hi, 

I hope things are going well for you.

I've contacted to Marta Kolorz (Sales/Suport person in Kontakt.io) through skype and she advised me to post my issue here.

I've read the documentation of Kontakt.io iOS SDK and implemented in my application. Delegate methods of KTKLocationManager are not always called. 

When didEnterRegion and didExitRegion delegate methods are called then I'm notifying my user through local notification. Sometime the methods are called and most of the time there is no response in the application. 

I've given my full effort to remove this issue but still I'm getting this problem. Please help me to remove this bugs.

Thanks
Amjad Khan

**Comment by hlebowicz-kontakt** [comment]
Hi Amjad,

Please attach a fragment of code where you are setting up **regions** that you want to monitor.

**Comment by amjad36** [comment]
Hi Hlebowicz, 

Here I've attached my code..... 

- (id)init
{
    self = [super init];
    
    if (self)
    {
        _locationManager = [KTKLocationManager new];
        _locationManager.delegate = self;
    }
    
    return self;
}

- (BOOL)application:(UIApplication *)application willFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    NSLog(@"%s", __func__);
    
    // Start monitoring iBeacon devices
    if ([KTKLocationManager canMonitorBeacons])
    {
        KTKRegion *region =[[KTKRegion alloc] init];
        region.uuid = @"f7826da6-4fa2-4e98-8024-bc5b71e0893e";
        
        [self.locationManager setRegions:@[region]];
        [self.locationManager startMonitoringBeacons];
    }
    
    // Ask user for permission to show alert when firing local notification
    if ([UIApplication instancesRespondToSelector:@selector(registerUserNotificationSettings:)]){
        [application registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeAlert|UIUserNotificationTypeBadge|UIUserNotificationTypeSound categories:nil]];
    }
    return YES;
}

- (void)locationManager:(KTKLocationManager *)locationManager didEnterRegion:(KTKRegion *)region
{
    NSLog(@"%s", __func__);

    UILocalNotification *notification = [[UILocalNotification alloc] init];
    notification.alertBody = @"Hello Percy! Welcome to Jim's office! Check out the offers we have for you";
    notification.soundName = UILocalNotificationDefaultSoundName;
    [[UIApplication sharedApplication] presentLocalNotificationNow:notification];
}

- (void)locationManager:(KTKLocationManager *)locationManager didExitRegion:(KTKRegion *)region
{
    NSLog(@"%s", __func__);
    
    UILocalNotification *notification = [[UILocalNotification alloc] init];
    notification.alertBody = @"Thanks for stopping by Percy! Check back for our next offer!";
    notification.soundName = UILocalNotificationDefaultSoundName;
    [[UIApplication sharedApplication] presentLocalNotificationNow:notification];
}

- (void)locationManager:(KTKLocationManager *)locationManager didChangeState:(KTKLocationManagerState)state withError:(NSError *)error
{
    if (state == KTKLocationManagerStateFailed) {
        [[[UIAlertView alloc] initWithTitle:@"iBeacon Alert" message:@"Something went wrong with your Location Services settings. Check OS settings." delegate:nil cancelButtonTitle:@"Ok" otherButtonTitles:nil, nil] show];
    }
}

- (void)locationManager:(KTKLocationManager *)locationManager didRangeBeacons:(NSArray *)beacons
{
    NSLog(@"Ranged beacons count: %lu", (unsigned long)[beacons count]);
}

**Comment by hlebowicz-kontakt** [comment]
Ok, I see your problem now.
You are listening only for region defined by proximity and all your beacons have the same one.
That means to get **didExitRegion** call you should be out of range of **all** those beacons. Additionally you will **not** get **didEnterRegion** until **didExitRegion** will be called.

It's not a bug this is how it's designed to work.

My advice for you is to define more detailed KTKRegion - add majors of those beacons.
This solution will give you the possibility to get those delegate's method calls per beacon.
I hope it's more clear for you now.

**Comment by amjad36** [comment]
All Beacons are kept at same place, so when I go out of range then it should be true for all the devices. So it should call didExitRegion. However, it is not not happening all the time. Could you comment on this, why this is happening?

I will also try to define more detailed KTKRegion (with major values) and get back to you.

**Comment by hlebowicz-kontakt** [comment]
The only issue in such a case with **didExitRegion** should be laggy execution. 
This method always is called with lag - when 'the device is 100% that it left specified region'.
This is how it's designed in iOS.

Additionally you should check if you have 0 devices ranged in 
````
- (void)locationManager:(KTKLocationManager *)locationManager didRangeBeacons:(NSArray *)beacons
````

**Comment by amjad36** [comment]
Hi Hlebowicz,

Now I've added Major value with UUID

if ([KTKLocationManager canMonitorBeacons])
    {
        KTKRegion *region = [[KTKRegion alloc] init];
        // illx Major: 49972
        region.uuid = @"f7826da6-4fa2-4e98-8024-bc5b71e0893e";
        region.major = [NSNumber numberWithInteger:49972];
        
        [self.locationManager setRegions:@[region]];
        [self.locationManager startMonitoringBeacons];
    }

But still the delegate methods (didEnterRegion and didExitRegion) are not called. Please help me to fix this issue.

Thanks
Amjad Khan

**Comment by amjad36** [comment]
Hi Hlebowicz,

Could you please revert? I'm waiting for your response..

Thanks
Amjad Khan

**Comment by hlebowicz-kontakt** [comment]
Hi,

I believe you are inside the region when you are trying to get those events.

To validate it please take the beacon that you add its major to your region. Take battery off, run the app, then put batter back - you should get *didEnterRegion* event for 100%.

Additionally when you are starting your app, do you have your beacon with major 49972 in the set of devices in didRangeBeacons call?

**Comment by amjad36** [comment]
Hi Hlebowicz,

Could you please provide me your Skype ID so we can communicate over it to resolve this issue.

Thanks
Amjad Khan

**Comment by hlebowicz-kontakt** [comment]
Hi Amjad36,

First thing first, we are not providing consultancy services for developers, especially with such a basic problems.
 
There are 2 more things that you can check:
1) did you add this [property](http://docs.kontakt.io/ios-sdk/quickstart/#ios-8-compatibility) to your project's **plist**?
2) download one of our sample apps and check if those methods are called.

Regards,
Lukasz

**Comment by amjad36** [comment]
Hi Hlebowicz,

I've added this property in my plist file. 
Ok, I'll download your sample app and check that it will working for me.

Thanks
Amjad Khan

**Comment by hlebowicz-kontakt** [comment]
Hi,

Did you succeed?

**Comment by amjad36** [comment]
Hi Hlebowicz,

I'm still struggling for the issue. and thank you for asking.

Thanks
Amjad Khan

**Comment by hlebowicz-kontakt** [comment]
Hi,

Sample app is not working for you?

**Comment by amjad36** [comment]
Hi,

Yes, sample app is not working as my requirement. didEnterRegion and didExitRegion methods are not called intermittently. This is the big issue for me and why it is not called always. 

Thanks
Amjad Khan

**Comment by Sumit19** [comment]
Hi @amjad36 , I am facing same problem,had you solved  this problem?

**Comment by Sumit19** [comment]
Hi @amjad36 , @hlebowicz-kontakt  , didEnterRegion and didExitRegion methods are not called in my case but didRangeBeacons work fine. Help me to shortcut this problem.

**Comment by amjad36** [comment]
Hi Sumit,

I did not get any final solution and I was unable to solve this issue with
the help of Kontakt.io developers. So I went for Estimote beacons.

Thanks
Amjad Khan

**Comment by Sumit19** [comment]
Hi @amjad36 , Thanks for reply, I have a question for you, basely i have 3  Kontakt.io beacons. My question is , is it possible to access these( Kontakt.io) beacons from Estimote SDK or to purchase Estimote beacons.

**Comment by rafaljanicki** [comment]
Hey Guys,

Sorry for not answering, @hlebowicz-kontakt is no longer with us and he didn't pass information to us about this ticket. Sorry again!

@stoprocent can answer, but please wait couple of days if you may. On Thursday we're finishing our sprint, so it's busy time for us and he may not be able to answer your questions so quickly. Plus, there are exciting things coming :-)

Best,
Rafal

**Comment by amjad36** [comment]
Definitely you have to buy Estimote iBeacon devices.

Thanks
Amjad Khan
