### ISSUE TITLE
Beacon detecting in background

### ISSUE THREAD

**Issue by wbroek** [kontaktio/SDK-iOS#16]
The SDK does not give any results when the app is in background and the beacon is in range for an hour?

```
KTKLocationManager *locationManager = [KTKLocationManager new];
locationManager.delegate = delegate;

NSMutableArray *beacons = [NSMutableArray new];

KTKRegion *tes1t = [[KTKRegion alloc]initWithUUID:@"ea8dd443-3f56-4093-9460"];
[beacons addObject:test1];

KTKRegion *test2 = [[KTKRegion alloc]initWithUUID:@4093-9460-726419636ac0"];
[beacons addObject:test2];

// etc for more beacons

[locationManager setRegions:prox];
[locationManager startMonitoringBeacons];
```

It's not seeing the beacons in the background even after an hour?

**Comment by jeffreyjackson** [comment]
@wbroek check your UUID, they don't seem to be the right format.

**Comment by wbroek** [comment]
@jeffreyjackson never mind de UUID; there are right! I'm not entering the original ones here, do you?
So assume they are correct!

**Comment by hlebowicz-kontakt** [comment]
@jeffreyjackson is right.
They are **NOT** correct! 
If you see any (format) similarity between yours and eg. "f7826da6-4fa2-4e98-8024-bc5b71e0893e" then I can't help you.
Btw. where did you get yours "proximities"?
