### ISSUE TITLE
Beacon detecting in background task

### ISSUE THREAD

**Issue by wbroek** [kontaktio/SDK-iOS#17]
When monitoring for beacons and the app goes in to the background, i create a background task (which runs for about 5 minutes and then iOS kills it). When i log the delegate for finding beacons it shows it finds 0 beacons when the app is in background

Setup (KTKLocationManager and KTKLocationManagerDelegate are defined in header)
```
    if ([KTKLocationManager canMonitorBeacons])
    {
        KTKRegion *region =[[KTKRegion alloc] init];
        region.uuid     = @"d14d5d27-6a07-4116-81c2-8146962a724e";        
        [self.locationManager setRegions:@[region]];
        [self.locationManager startMonitoringBeacons];
    }
```

Detection (KTKBluetoothManager and KTKBluetoothManagerDelegate are defined in delegate):
```
   self.bluetoothManager = [[KTKBluetoothManager alloc] init];
   self.bluetoothManager.delegate = self;
   [self.bluetoothManager startFindingDevices];

   - (void)bluetoothManager:(KTKBluetoothManager *)bluetoothManager didChangeDevices:(NSSet *)devices
   {
       NSLog(@"I found %lu Kontakt iBeacons near you", devices.count);
   }
```

**Comment by stoprocent** [comment]
Hi
Bluetooth manager is not really created for scanning beacons in the background. Youy should be using Location Manager to do that. If still you need to scan devices in the background using CoreBluetooth u have to select "Uses Bluetooth LE accessories" flag in background modes section in your project :) http://cl.ly/cEcZ
