### ISSUE TITLE
"missing required architecture i386" in file libkontakt-ios-sdk.a

### ISSUE THREAD

**Issue by RickRockhold** [kontaktio/SDK-iOS#18]
I'm using the latest SDK with Xcode 7. I can build for the simulator using iPhone 5s (8.1) and later, but building for iPhone 5 gives me this error.

**Comment by Tulakshana** [comment]
I have the same problem

**Comment by RickRockhold** [comment]
Is anybody monitoring this channel? It's been over three weeks without a response.

**Comment by stoprocent** [comment]
Hi, I'm sorry guys for late response. We have a big release comming in very short time. It will be all new SDK rewriten from the ground up. Security features, iOS 8+, Swift 2 friendly, Bitcode enabled and many many more new features. I will update this ticket as soon as we release it.

**Comment by RickRockhold** [comment]
Any estimate? We're prepping for a release...

**Comment by stoprocent** [comment]
Hi! About 2 weeks

**Comment by aamctustwo** [comment]
@stoprocent Any update on this release?

**Comment by sergeyzhukov** [comment]
2 weeks ended two weeks ago. any news?

**Comment by RickRockhold** [comment]
Our product is on hold waiting for this. Delays are one thing (they happen), but lack of communication is terrible. What's the latest guess?

**Comment by stoprocent** [comment]
Hi
I'm sorry for all the delays. SDK will be released next week. We have a global beaconvalley hackathon on 21st and we want people to use it then. I must say there was a lot to cover in the documentation and that took a lot of time. I fully understand that communication wasn't the best over the last few weeks, but I promise it will change after new SDK and App will be officially released.
I'm pushing now to create a much better community around our platforms and it will happen, but I rather take a bit longer route but more stable.

Sorry again and please feel free to contact me at m.serafin@kontakt.io and I will send you an email when SDK will be released.

**Comment by RickRockhold** [comment]
Another deadline gone, no feedback. Is there a new ETA?

**Comment by sergeyzhukov** [comment]
I think they don't want to have a lot customers, as I can see by their support

**Comment by RickRockhold** [comment]
We're all developers and understand bugs; not all problems are replicable or easily solved.

This isn't one of those situations. 

This is a compiler setting that excludes an entire class of devices. We don't need a big release. We don't need rewritten code. We need someone to hit "compile". 

Long delays, no communication. Our app can't be approved because of this problem, our business is losing opportunities. 

We've made promises based on yours, and are suffering from it. We're going to start investigating beacons from another manufacturer just to protect ourselves. 

Is there an actual, dependable, realistic release date?

**Comment by stoprocent** [comment]
Hi Rick

We have a bug, CoreBluetooth related that is probably on Apple's side and as you maybe know its not easy to get quick support from them. Im very sorry for all the incovinience but trust me I'm on it almost 24/7. 

I sent you an email with a solution I dont want to publish here so please check your email.

Best regards

M

**Comment by Tulakshana** [comment]
Hi Rick,
If you could share the bug you have with us, somebody might be able to help you out.

**Comment by RickRockhold** [comment]
Well, nobody's even providing an estimate now. I'm giving up, moving on to another manufacturer...

**Comment by ernestom** [comment]
@RickRockhold Estimote worked really well for me.

**Comment by rafaljanicki** [comment]
Hello,

We are very sorry about the delay, it's because we ran into many blockers on a way which we haven't anticipated. Also, iOS 9 was released in a meantime and we decided to support it from a day 1 instead of releasing fixes.

@RickRockhold please accept my apologies. We don't provide estimates anymore due to various bugs which we have encountered on a way. We're on finishing line here and we should be ready to provide you with a solution in following days, but we don't want to give any dates until we actually have the SDK & app fully ready.

Again, we're very sorry for that, but we want to deliver the best solution which is both optimized and easy to use.

**Comment by nhokkuteluv** [comment]
Any good news now? I got the same issue.

**Comment by byteblocks** [comment]
I ran into similar issues yesterday. I got response from technical support that all these bitcode and i386 related issues are going to be addressed in next release. ETA of next release has been given "BY END OF THIS MONTH". Let's see if ETA holds?

**Comment by RickRockhold** [comment]
Yeah, I was told "end of the month" in October. Cross your fingers...

**Comment by nhokkuteluv** [comment]
how about now? No one monitor this channel? Could you please answer us when this issue will be fixed?

**Comment by rafaljanicki** [comment]
Hello,

We have uploaded a new and final app to App Store today and are waiting for an acceptance. As soon as we get it, we are releasing the whole package including new SDK.

Best regards,
Rafal

**Comment by nhokkuteluv** [comment]
Thank @rafaljanicki for your fast reply. I'm going to contact a guy who represented Kontakt at Beijing: Filip Zielinski  to complain about this. But thank for your answer, I and my team will be waited for your promise.

**Comment by nhokkuteluv** [comment]
any update? It've been 8 days, Review from Apple just take 7 days.

**Comment by rafaljanicki** [comment]
Unfortunately not around Christmas and NYE, we are still waiting for the
acceptance.

On Tue, Jan 5, 2016 at 4:57 AM, Phong Nguyen <notifications@github.com>
wrote:

> any update? It've been 8 days, Review from Apple just take 7 days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kontaktio/SDK-iOS/issues/18#issuecomment-168886846>.
>



-- 
Best regards,

[image: Rafal Janicki]
Rafal JanickiCTO

rafal@kontakt.io

skype: rafal_janicki

www.kontakt.io

office: +48 123 793 445
[image: Kontakt.io] <http://kontakt.io/>[image: Facebook]
<https://www.facebook.com/kontakt.io> [image: Twitter]
<https://twitter.com/kontakt_io> [image: LinkedIn]
<https://www.linkedin.com/company/kontakt-io> [image: Google+]
<https://plus.google.com/106304420610581266611/about>

**Comment by stoprocent** [comment]
Guys I know it's been a long time but we are finally done :)
Go and have alook at https://github.com/kontaktio/kontakt-ios-sdk

From now on I will respond to all the issues ASAP!
