### ISSUE TITLE
Getting Issue with this line in the X-Code example for swift

### ISSUE THREAD

**Issue by NicholasHeaney** [kontaktio/SDK-iOS#19]
![screen shot 2015-09-17 at 4 16 54 pm](https://cloud.githubusercontent.com/assets/13197920/9948313/5d76a408-5de5-11e5-9ac6-fab054e6e85a.png)

self.locationManager.delegate = self

returning an error "Cannot assign value of type 'KTKLocationManagerDelegate' to a value of type 'KTKLocationManagerDelegate?'

**Comment by stoprocent** [comment]
Hi 

Just add ! and problem solved :) We are also releasing new SDK Swift 2 friendlier ;) stay tuned
