### ISSUE TITLE
Bad deprecated warning for KTKBluetoothDevice disconnect

### ISSUE THREAD

**Issue by RickRockhold** [kontaktio/SDK-iOS#2]
KTKBluetoothDevice.disconnect has a deprecated warning, indicating that I should use KTKBeaconDevice.disconnect. Ok, but KTKBeaconDevice inherits from KTKBluetoothDevice and overrides disconnect, so this code:

KTKBeaconDevice* device = ...;
[device disconnect];

still gives me the deprecated warning.

**Comment by hlebowicz-kontakt** [comment]
I know it's a little bit confusing but there is no better option to deprecate old method in base class and leave working one in child.

**Comment by RickRockhold** [comment]
It's more than confusing; I spend several hours trying to understand how to disconnect from the beacon, because the code told me what I was doing was wrong. Plus, we have a "no warning" policy for our builds (not uncommon), so we may have to stop using your product. There are at least three other viable solutions:

1. Remove the base class disconnect method. This will cause a compile error for anyone trying to call it. It doesn't give them a deprecated warning that explains the alternative, but this is a diminishing problem: Isn't it better than giving all 'new' api users a compile error?

2. You recently added a new connect method (connectWithPassword:andError:), and deprecated older connect methods (authorize, setPassword:, etc). How about a new disconnectBeacon method?

3. Don't mark the old method as deprecated; have the base class raise an exception if it's actually called. Sure, it's less desirable to have a runtime failure instead of a compile time failure, but right now there's a compile-time failure that can never be avoided...

I understand the need for new APIs and deprecating the old ones, but the current situation makes no sense--the only disconnect method tells me that I shouldn't use it. That's not simply confusing, it's blatantly false. It's better to give transitioning API users weaker documentation during a transition than to give all new API users outright bad information.

Thanks,
Rick

**Comment by hlebowicz-kontakt** [comment]
1. Honestly removing old method without backward compatibility is not good solution.
2. Additionally we decided not to change name of this method because it's ok.
3. For backward compatibility it's a nightmare.

That said, you have all needed info to solve you problem in warning message and header files - you know that this warning is more or less temporary thing and you didn't do anything wrong.

I appreciate your comment, we are trying to avoid such a situations, but sometimes it's the best solution.

**Comment by RickRockhold** [comment]
Ok, thanks for your time. Although I’ve never before encountered a programming situation where intentionally adding a false error is the “best solution”.

**Comment by hlebowicz-kontakt** [comment]
No problem.
Still it's warning not error and it's there to warn you that you should not use this method with base class objects.
Btw. deprecated means it's obsolete(will be removed in the future) but it's still working.

**Comment by RickRockhold** [comment]
Ok, how about a compromise: Change the deprecated message to something like "Use - (void)disconnect from KTKBeaconDevice, although this warning will still appear”. As it exists, it tells me there’s a problem, tells me what to do to fix it (which I was already doing), then continues to tell me there’s a problem.

**Comment by hlebowicz-kontakt** [comment]
Yup, message like this will be less confusing.
Thanks
