### ISSUE TITLE
Conflict when Kontakt.io and Estimote SDKs are used by a project

### ISSUE THREAD

**Issue by Saurman** [kontaktio/SDK-iOS#20]
See screenshot below
![screen shot 2015-10-07 at 11 06 34 am](https://cloud.githubusercontent.com/assets/1107926/10337119/52d62020-6d06-11e5-9487-bc36791d8304.png)

**Comment by stoprocent** [comment]
From what I see this is related to common layer for OTA firmware library that is provided by nordic semiconductors. Both Estimote and Kontakt beacons are based on NRF51 chip. Our new SDK will be released very soon and it has our custom firmware update library so this wont happen. There is no fix i can suggest at the moments
