### ISSUE TITLE
Beacon detecting in background IOS 9.0.2

### ISSUE THREAD

**Issue by svfelipe** [kontaktio/SDK-iOS#21]
Hi,

I need help with IOS SDK running in Background, the ideia is send notification to user when he enter on iBeacon area, works only with App in foreground mode.

We use the last version o IOS SDK 9.0.2 (and last version of kontakt.io SDK).

The code is the TestApp Sample based (https://github.com/kontaktio/TestAppWithKontaktSDK-iOS), this part don't work with console output too:

#pragma mark - KTKLocationManagerDelegate

- (void)locationManager:(KTKLocationManager *)locationManager didChangeState:(KTKLocationManagerState)state withError:(NSError *)error
{
    if (state == KTKLocationManagerStateFailed)
    {
        NSLog(@"Something went wrong with your Location Services settings. Check OS settings.");
    }
}

- (void)locationManager:(KTKLocationManager *)locationManager didEnterRegion:(KTKRegion *)region
{
    NSLog(@"Enter region %@", region.uuid);
}

- (void)locationManager:(KTKLocationManager *)locationManager didExitRegion:(KTKRegion *)region
{
    NSLog(@"Exit region %@", region.uuid);
}

- (void)locationManager:(KTKLocationManager *)locationManager didRangeBeacons:(NSArray *)beacons
{
    NSLog(@"Ranged beacons count: %lu", (unsigned long)[beacons count]);
}

Thanks

**Comment by svfelipe** [comment]
Background modes On:
- Location Updates
- Uses BT LE
- BG fetch
- Remote Notifications

**Comment by stoprocent** [comment]
Hi
I would love to help but there isnt too much information for me to know what is going on.
Can you provide some more code? For regions monitoring to work you have to set location/beacons manager delegate in applicationDidFinishLaunching in your app delegate. Just code sample from what are you calling in location/beacons delegate methods isnt enough.

**Comment by svfelipe** [comment]
Hi, thank you for reply.

Full Code:

#import "AppDelegate.h"

#import "KontaktSDK.h"
#import "KTKBluetoothManager.h"

static NSString *KontaktProximityUUID = @"f7826da6-4fa2-4e98-8024-bc5b71e0893e";


@interface AppDelegate ()
<KTKLocationManagerDelegate>

@property KTKLocationManager *locationManager;
@property NSDate *datePicker;

@end


@implementation AppDelegate

- (id)init
{
    self = [super init];
    
    if (self)
    {
        _locationManager = [KTKLocationManager new];
        _locationManager.delegate = self;
        
        return self;
    }
    
    return nil;
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // Override point for customization after application launch.
    
    if ([KTKLocationManager canMonitorBeacons])
    {
        KTKRegion *region =[[KTKRegion alloc] init];
        region.uuid     = KontaktProximityUUID;
        region.major    = [NSNumber numberWithLong:55555];
        region.minor    = [NSNumber numberWithLong:10114];
        
        KTKRegion *region2 =[[KTKRegion alloc] init];
        region2.uuid    = KontaktProximityUUID;
        region2.major   = [NSNumber numberWithLong:55555];
        
        [self.locationManager setRegions:@[region, region2]];
        [self.locationManager startMonitoringBeacons];
    }
    
    return YES;
}

- (void)applicationWillResignActive:(UIApplication *)application {
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
}

- (void)applicationDidEnterBackground:(UIApplication *)application
{
    
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
    

 }

- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
}

- (void)applicationWillTerminate:(UIApplication *)application {
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
}

#pragma mark - KTKLocationManagerDelegate


- (void)locationManager:(KTKLocationManager *)locationManager didChangeState:(KTKLocationManagerState)state withError:(NSError *)error
{
    if (state == KTKLocationManagerStateFailed)
    {
        NSLog(@"Something went wrong with your Location Services settings. Check OS settings.");
    }
}

- (void)locationManager:(KTKLocationManager *)locationManager didEnterRegion:(KTKRegion *)region
{
    NSLog(@"Enter region %@", region.uuid);
}

- (void)locationManager:(KTKLocationManager *)locationManager didExitRegion:(KTKRegion *)region
{
    NSLog(@"Exit region %@", region.uuid);
}

- (void)locationManager:(KTKLocationManager *)locationManager didRangeBeacons:(NSArray *)beacons
{
    NSLog(@"Ranged beacons count: %lu", (unsigned long)[beacons count]);
}

@end

**Comment by svfelipe** [comment]
Hi,
I Regenerate the iBeacon Proximity UUID, and work fine now.
Thanks!

**Comment by stoprocent** [comment]
Great! Please keep in mind that regions registered are stored by iOS until you stop monitoring them.

Please remeber if you keep registering regions without unregistering them you may git the limit of 20 regions per app :)

Apple Documentation:
https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/occ/instp/CLLocationManager/monitoredRegions
