### ISSUE TITLE
proximity is always KTKEddystoneDeviceProximityUnknown

### ISSUE THREAD

**Issue by Julchen123** [kontaktio/SDK-iOS#22]
Hello,

I am developing an iOS App with Eddystones using the KontaktSDK.

When I run my App on my device (iPhone 6+, iOS 9.1) all off my Eddystones where found by KTKBluetoothManagerDelegate. I have set a breakpoint into the "didChangeEddystones" method to have a look at the Eddystones. The problem is, that the proximity is always KTKEddystoneDeviceProximityUnknown.
The txPower is -77 and the accuracy is 2.22..

Could not find any help in support forms. Can you please help me?

Greats,
Marlene

**Comment by mixdesign** [comment]
Hello Kontakt.io, are you here?
Should we deal with your beacons?
Any support?

**Comment by stoprocent** [comment]
Hi

Yes it's possible as in our current SDK we didn't calculate proximity yet. 
It is in new SDK that is coming after the weekend.
Just putting final touches now. 

M

**Comment by mixdesign** [comment]
Any news on update?

**Comment by stoprocent** [comment]
Hi @mixdesign 

We have been super busy working on new SDK and that is why all replies were taking ages... I know and I'm sorry. You should go and have a look at our new iOS SDK at https://github.com/kontaktio/kontakt-ios-sdk

**Comment by mixdesign** [comment]
@stoprocent Good news. Thank you!
