### ISSUE TITLE
Getting KontaktSDK error 5

### ISSUE THREAD

**Issue by nick-holmes** [kontaktio/SDK-iOS#23]
Using - (BOOL)beaconUpdate:(KTKBeacon *)beacon withError:(NSError **)error;
I keep receiving this issue. It was working perfectly earlier in the week and after making no edits to my code I've begun to get this.

Using the latest SDK version (6.2).

Code snippet:

                KTKClient *client = [KTKClient new];
                [client setApiKey:@"my api key here"];
                // Format update object
                KTKBeacon *updated = [KTKBeacon new];
                updated.uniqueID = beacon.uniqueID;
                updated.firmware = [NSString stringWithFormat:@"%@",beacon.firmwareVersion];
                updated.name = beacon.name;
                updated.major = [NSNumber numberWithInt:[[dict objectForKey:@"major"] intValue]];
                updated.minor = [NSNumber numberWithInt:[[dict objectForKey:@"minor"] intValue]];
                updated.power = [NSNumber numberWithInt:[[dict objectForKey:@"power"] intValue]];
                updated.interval = [NSNumber numberWithInt:[[dict objectForKey:@"interval"] intValue]];
                updated.password = [dict valueForKey:@"password"];
                
                // Begin update
                NSError *updateError;
                if(![client beaconUpdate:updated withError:&updateError]){
                    [self logText:[NSString stringWithFormat:@"Error: %@", updateError]];
                }

 What's going on?

**Comment by FranciZ** [comment]
I have the same issue on iOS 9.1

**Comment by stoprocent** [comment]
Hi Guys
We are tracking this issue now. It's related to our Cloud API.
Stay tuned

**Comment by PCTIDM** [comment]
Any update on this? It's been almost a month.

**Comment by stoprocent** [comment]
Hi

Sorry for late replies. It won't happen again I promise! You should go and have a look at our latest iOS SDK at https://github.com/kontaktio/kontakt-ios-sdk
