### ISSUE TITLE
Problem with iOS 9.2

### ISSUE THREAD

**Issue by kashyap-v** [kontaktio/SDK-iOS#24]
Hi,
My app was working with iOS 8.1. But, when i updated my device to iOS 9.2, it stopped working.
When i launch my app, it is not entering didRangeBeacons of locationManager. Please let me know the solution
Thank you,
Kashyap

**Comment by byteblocks** [comment]
Do you have "NSLocationAlwaysUsageDescription" and/or "NSLocationWhenInUseUsageDescription" entries in .plist file of your application? Lack of these entries causes the application to silently stop getting range/location updates from location services.

**Comment by kashyap-v** [comment]
Thanks for the suggestion, but, I already made that change for making it work in ios8
Anyway, the problem got solved. After updating to ios9.2, i had to restart bluetooth!

**Comment by stoprocent** [comment]
Hi Guys! 

Before I will close this ticket I wanted to invite you to check out new iOS SDK at https://github.com/kontaktio/kontakt-ios-sdk
