### ISSUE TITLE
How to discover beacons when application is in sleep mode

### ISSUE THREAD

**Issue by AnushreeKala** [kontaktio/SDK-iOS#25]
I want my iOS application to discover Contact beacons when my app is in Background or sleep mode.
I wrote this code in  applicationDidEnterBackground and also added pList properties
<key>NSLocationAlwaysUsageDescription</key>
	<string>Tracks the location of the user</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Tracks the location of the user</string>
	<key>UIApplicationExitsOnSuspend</key>
	<false/>
	<key>UIBackgroundModes</key>
	<array>
		<string>bluetooth-central</string>
		<string>bluetooth-peripheral</string>
		<string>location</string>
		<string>remote-notification</string>
	</array>

 if (nil == self.locationManager)
        self.locationManager = [[CLLocationManager alloc] init];
    self.locationManager.delegate = self;
    self.locationManager.desiredAccuracy = kCLLocationAccuracyBest;
    // Set a movement threshold for new events.
    self.locationManager.distanceFilter = 500; // meters
    [self.locationManager startUpdatingLocation];

But it doesn't work when application is in background mode.

Any help would be appreciated. Thanks in advance.

**Comment by stoprocent** [comment]
Hi @AnushreeKala we will be shutting down this version of SDK so my advice is to go and have a look at the new SDK at https://github.com/kontaktio/kontakt-ios-sdk
