### ISSUE TITLE
Not getting beacon information in "didRangeBeacons"

### ISSUE THREAD

**Issue by Rajesh-162** [kontaktio/SDK-iOS#26]
I have added SDK & code as per kontakt.io doc and also getting call in the method "didRangeBeacons" but getting the empty array of beacons.

Method is as follows:

`- (void)beaconManager:(KTKBeaconManager*)manager didRangeBeacons:(NSArray <CLBeacon *>*)beacons
             inRegion:(__kindof KTKBeaconRegion*)region{
    CLBeacon *foundBeacon = [beacons firstObject];

    if (self.delegate && [self.delegate respondsToSelector:@selector(didFoundiBeacon:)]) {
        [self.delegate didFoundiBeacon:foundBeacon];
    }
    
    NSLog(@"Ranged beacons count: %d", [beacons count]);
    
    // We can retrieve the beacon data from its properties
    NSString *uuid = foundBeacon.proximityUUID.UUIDString;
    NSString *major = [NSString stringWithFormat:@"%@", foundBeacon.major];
    NSString *minor = [NSString stringWithFormat:@"%@", foundBeacon.minor];
    
    NSLog(@"%@",uuid);
    NSLog(@"%@",major);
    NSLog(@"%@",minor);
}`

Am I missed out anything here? Please let me know.

**Comment by stoprocent** [comment]
Hi @Rajesh-162 

Are you using old SDK or a new one? https://github.com/kontaktio/kontakt-ios-sdk

This repository is for a depricated SDK. 
If you using new one please move your issue there.

Also I need to see more code as this is just a delegate call and key fact here is how you initialize ranging.

**Comment by Rajesh-162** [comment]
I have done it please have a look...
