### ISSUE TITLE
txPower

### ISSUE THREAD

**Issue by dimohamdy** [kontaktio/SDK-iOS#7]
How I can get txPower of beacons when start monitoring a specific region?

**Comment by hlebowicz-kontakt** [comment]
There is no relation between monitoring region and getting txPower of beacon.
To get txPower of specified beacon you have to connect to it with password and then read this value from  characteristic kKTKCharacteristicDescriptorTypeTxPowerLevel. If you are interested in reading other properties/characteristics you can find them there - http://docs.kontakt.io/ios-sdk/appledocs/Classes/KTKCharacteristicDescriptor.html
