### ISSUE TITLE
SDK doesn't initialize if NSLocationWhenInUseUsageDescription is specified in plist.info

### ISSUE THREAD

**Issue by Meltor22** [kontaktio/SDK-iOS#9]
The SDK doesn't initialize if NSLocationWhenInUseUsageDescription is specified in plist.info.
It's only working with NSLocationAlwaysUsageDescription.

**Comment by hlebowicz-kontakt** [comment]
Yes this is expected behavior as it stays in quick start http://docs.kontakt.io/ios-sdk/quickstart/#add-ios-8-compatibility.
Only with this settings you are able to get notifications when app is in background.

**Comment by Meltor22** [comment]
I think i didn't express the problem enough.

I don't want to use background updates in this case, so i want to use just NSLocationWhenInUseUsageDescription. But then the SDK doesn't work. 

I tried it with my own app and also with the iOS-Example - but just don't initialize with the setting NSLocationWhenInUseUsageDescription

**Comment by hlebowicz-kontakt** [comment]
SDK is only working with **NSLocationAlwaysUsageDescription** and this is **intended** behavior.

If you don't want to get background updates just call:
```- (void)stopMonitoringBeacons;``` 
on your **KTKLocationManager** in **AppDelegate's**
 ```- (void)applicationDidEnterBackground:(UIApplication *)application;```
